Lesson 1: Add Adminer Docker container config
f-m-t-t-m/fefu_backend_2_3 pull request #1
Opened 2021-09-22 07:11 UTC by f-m-t-t-m

2021-09-22 08:35 UTC, f-m-t-t-m commented
@chrn-feip

2021-09-22 09:56 UTC, f-m-t-t-m commented
@chrn-feip

2021-09-28 14:25 UTC, chrn-feip requested changes

2021-09-28 14:25 UTC, chrn-feip commented on docker-compose.yml
> +            - adminer
Это не нужно, приложение никак в действительности не использует Adminer, в отличие от остальных контейнеров.

2021-09-28 14:25 UTC, chrn-feip commented on docker-compose.yml
> +            - 8080:8080
Совсем хорошо будет вынести порт в .env (и .env.example, чтобы он попал в коммит) и использовать эту переменную окружения с дефолтным значением. См. как сделаны ports в laravel.test. Так гибче управлять конфигурацией и в случае изменения порта понадобится только поменять .env (который не лежит в репозитории) вместо изменения docker-compose.yml (который под контролем версий) и деплоя изменений на сервер/коммит в репозиторий.

2021-09-28 15:12 UTC, chrn-feip commented on docker-compose.yml
> +            - 8080:8080
Не забыть, что если вводится новая переменная окружения, то надо её также добавить в .env.example, добавить к коммиту.

2021-09-29 05:14 UTC, merged