Lesson 10: Add web and API auth and profile
f-m-t-t-m/fefu_backend_2_3 pull request #10
Opened 2021-11-27 07:00 UTC by f-m-t-t-m

2021-12-03 13:37 UTC, chrn-feip requested changes

2021-12-03 13:37 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthController.php
> +            'login' => 'required',
Для логина и пароля можно задать ограничение на максимальную длину строки, чтобы сразу поругаться, а не пытаться скормить БД в запросе что-то очень большое.

2021-12-03 13:37 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthController.php
> +        $user = User::query()->where('login', $validated['login'])->first();
Можно не проверять руками логин и хэшированный пароль, а вызвать Auth::attempt, например так: 

 if (!Auth::attempt(['login' => $validated['login'], 'password' => $validated['password']]))
            return response()->json(['message' => 'Неверный логин или пароль'], 422);

$user = User::query()->where('login', $validated['login'])->first();

2021-12-03 13:37 UTC, chrn-feip commented on app/Http/Controllers/WebLoginController.php
> +                'login' => ['required'],
Аналогично про ограничение на верхнюю границу размера строки

2021-12-03 13:37 UTC, chrn-feip commented on app/Http/Controllers/WebProfileController.php
> +        return view('profile', ['user'=>$user]);
Лучше передавать в шаблон ресурс как массив. Это уже подготовленные отформатированные данные и невозможность фронтам во вьюшках как-то испортить данные в БД через использование модели.

2021-12-03 13:37 UTC, chrn-feip commented on composer.json
> +        "doctrine/dbal": "^3.1",
Это зачем понадобилось?

2021-12-03 13:37 UTC, chrn-feip commented on resources/views/layouts/app.blade.php
> +    @if (\Illuminate\Support\Facades\Auth::check())
В шаблонах тоже можно использовать use, в @php @endphp блоке, желательно в начале файла. Тогда тут останется Auth::check(), лаконично и не загромождает код вью.

2021-12-03 13:37 UTC, chrn-feip commented on resources/views/login.blade.php
> +    @if (session('error'))
Что тут может быть за ошибка?

2021-12-03 13:37 UTC, chrn-feip commented on routes/api.php
> +Route::middleware('auth:sanctum')->post('/logout', [ApiAuthController::class, 'logout']);
Можно объединить в группу с общим middleware

2021-12-03 13:37 UTC, chrn-feip commented on routes/web.php
> +Route::get('/logout', WebLogoutController::class)->name('logout')
Аналогично, группа с общим посредником

2021-12-03 14:45 UTC, f-m-t-t-m commented on composer.json
> +        "doctrine/dbal": "^3.1",
Чтобы обновить модель юзера

2021-12-03 16:07 UTC, chrn-feip commented on composer.json
> +        "doctrine/dbal": "^3.1",
Что значит "обновить модель юзера"? Структура БД обновляется миграцией. Если нужно автодополнение свойств модели, то можно вручную прописать PHPDoc \@property.

2021-12-04 03:28 UTC, f-m-t-t-m commented on composer.json
> +        "doctrine/dbal": "^3.1",
https://laravel.com/docs/8.x/migrations#modifying-columns

2021-12-04 05:47 UTC, f-m-t-t-m commented on resources/views/login.blade.php
> +    @if (session('error'))
Неправильный логин/пароль.
return redirect()->route('login')->with('error', 'Wrong login or password');

2021-12-04 06:08 UTC, f-m-t-t-m commented on resources/views/layouts/app.blade.php
> +    @if (\Illuminate\Support\Facades\Auth::check())
Не получилось так сделать. Импортируется только в этом php блоке и нельзя использовать в шаблоне. Сделал через @inject

2021-12-09 14:47 UTC, chrn-feip requested changes

2021-12-09 14:47 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthController.php
> +            'login' => 'required|unique:users|between:5, 30|regex: /^[(?i)a-z(?-i)\.-]+$/',
`/^[a-z\.-]+$/i`

2021-12-10 11:27 UTC, merged