Lesson 11: Add Role-based access control and News API
f-m-t-t-m/fefu_backend_2_3 pull request #11
Opened 2021-12-10 15:01 UTC by f-m-t-t-m

2021-12-14 16:28 UTC, chrn-feip requested changes

2021-12-14 16:28 UTC, chrn-feip commented on app/Http/Resources/NewsResource.php
> +            'title' => $this->title,
Ещё бы в ресурсе отдавать url новости (генерировать через маршрут со слагом)

2021-12-14 16:28 UTC, chrn-feip commented on routes/api.php
> +       return response()->json(['message' => 'News not found']);
404 статус ответа потеряли

2021-12-14 16:28 UTC, chrn-feip commented on app/Providers/AuthServiceProvider.php
> +        Post::class => PostPolicy::class,
Для комментария политику не надо зарегистрировать? Или наоборот для поста убрать (если не ошибаюсь, нейминг у вас соблюдён в достаточной степени, чтобы Laravel автоматически сматчил модели и политики).

2021-12-14 16:28 UTC, chrn-feip commented on database/migrations/2021_11_26_135211_update_users_table.php
> +            $table->string('role')->nullable();
Лучше всего такое поле сделать enum с отдельным классом Enum с числовыми константами (как мы делали для пола на лекции про форму и валидацию). В коде использовать значение константы из класса. И в БД её писать. Потом, когда появится админка, вы сможете на основе Enum класса сделать поле-селект, что сведёт на нет вероятность ошибки в заполнении роли.

2021-12-14 16:41 UTC, chrn-feip commented on routes/api.php
> +        'news' => 'id'
слаг

2021-12-14 16:42 UTC, chrn-feip commented on database/migrations/2021_11_26_135211_update_users_table.php
> +            $table->string('role')->nullable();
А что это за новости с модификацией файла миграций? Новое изменение - новый файл миграции.

2021-12-16 16:59 UTC, f-m-t-t-m commented on app/Providers/AuthServiceProvider.php
> +        Post::class => PostPolicy::class,
Не надо, забыл убрать.

2021-12-17 09:04 UTC, chrn-feip requested changes

2021-12-17 09:04 UTC, chrn-feip commented on database/migrations/2021_11_26_135211_update_users_table.php
> -            $table->string('email')->unique()->nullable(false)->change();
Не трогайте это поле. Оно не нужно для задачи. Да и это опять изменение кода в файле уже выполненной миграции.

2021-12-17 10:21 UTC, f-m-t-t-m commented on database/migrations/2021_11_26_135211_update_users_table.php
> -            $table->string('email')->unique()->nullable(false)->change();
Эта ошибка у меня с одной из прошлых д/з, в down() не должно было быть у email unique(), т.к. он и так уже unique.

2021-12-17 10:35 UTC, merged