Lesson 7: Add redirecting middleware
f-m-t-t-m/fefu_backend_2_3 pull request #7
Opened 2021-11-02 06:14 UTC by f-m-t-t-m

2021-11-04 07:34 UTC, chrn-feip requested changes

2021-11-04 07:34 UTC, chrn-feip commented on routes/web.php
> +use App\Http\Middleware\RedirectFromOldSlug;
Стало не нужно? Удалите тогда из коммита

2021-11-04 07:34 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +            $this->error("ERROR");
Текст ошибки-то задайте конкретный и подходящий ошибке

2021-11-04 07:34 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        DB::transaction(function () use ($news, $oldSlug, $newSlug){
В задаче уточнены требования, тут не хватает проверки и возможного удаления записи из таблицы редиректов.

2021-11-04 07:34 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        $result = $request->session()->get('result', 'fail');
Зачем вам этот параметр в сессии? Вам нужно выполнять логику из if в любом случае, если найдена запись в таблице редиректов.

2021-11-04 07:34 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +                    ->where('id', '>', $redirect->id)
Тут надёжнее ориентироваться на created_at. У вас может быть миграция данных из другого источника, при которой id перестанет отражать актуальную последовательность смены слагов.

2021-11-04 09:45 UTC, f-m-t-t-m commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        $result = $request->session()->get('result', 'fail');
Потому что иначе был зацикленный редирект, из-за того, что после редиректа опять отрабатывает посредник.

2021-11-04 09:51 UTC, f-m-t-t-m commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        $result = $request->session()->get('result', 'fail');
Логика из иф и выполняется всегда. Иф не будет выполняться только после редиректа, чтобы не было цикла и сразу переходило на найденную страницу.

2021-11-05 08:55 UTC, chrn-feip requested changes

2021-11-05 08:55 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +            $redirect = Redirect::where('old_slug',  parse_url($newUrl, PHP_URL_PATH))->first();
Не нужно делать first, потом отдельно проверять на  null. В конструкторе запроса можно не только выбирать строки из таблицы согласно условиям, но и удалять. Т.е. можно сразу метод delete вызвать вместо first.

2021-11-05 09:41 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        $oldUrl = route('news_item', ['slug' => $oldSlug]);
У route метода есть третий параметр, изучите

2021-11-09 13:12 UTC, merged