Lesson 9: Add posts and comments with API
f-m-t-t-m/fefu_backend_2_3 pull request #9
Opened 2021-11-18 07:47 UTC by f-m-t-t-m

2021-11-18 14:21 UTC, chrn-feip requested changes

2021-11-18 14:21 UTC, chrn-feip commented on routes/api.php
> +Route::apiResource('posts.comments', CommentController::class)
А здесь где scoped?

2021-11-18 14:21 UTC, chrn-feip commented on database/seeders/DatabaseSeeder.php
> +            UserSeeder::class,
Повторный запуск сидера делали? Скорее всего упадёт из-за truncate в каждом отдельном сидере и ограничения на внешний ключ. Нужно либо тут сделать предварительно удаление в обратной последовательности - от комментов к юзерам. Либо можете попробовать отключать проверку FK командами disableForeignKeyConstraints и enableForeignKeyConstraints (ищите их тут https://laravel.com/api/8.x).

2021-11-18 14:21 UTC, chrn-feip commented on app/Models/Comment.php
> +class Comment extends Model
scopeOrdered и тут актуален будет

2021-11-18 14:21 UTC, chrn-feip commented on app/Http/Controllers/PostController.php
> +            return response()->json(['error' => $msg], 400);
1. Почему только первое сообщение? Верните все. Пусть это будет массив errors, а внутри массив с ключи-атрибутами, которые не прошли валидацию.
2. Для ответа об ошибках валидации больше подходит статус 422

2021-11-18 14:21 UTC, chrn-feip commented on app/Http/Controllers/PostController.php
> +            'title' => 'sometimes|required|max:100',
При создании все атрибуты строго отрицательны. Не могут какие-то не прийти.

2021-11-18 14:21 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
1. А разве Post не будет автоматически определён маршрутом по указанному там идентификатору в scoped?
2. Можно ещё потестировать случай, когда в урле слаг от одного поста, а id коммента от другого. Так вы поймёте, вычитывается ли пост при обработке маршрута и откуда вычитывается коммент - из отношения у загруженного поста или сам по себе из таблицы. Как только поймёте, так и решится вопрос нужности проверки ниже или необходимости другой.

Кстати, если говорить о first, то он может вернуть null, а попытка взять ->id от null приведёт к падению.

2021-11-18 14:21 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +            'text' => 'sometimes|required|max:150'
Для создания все атрибуты строго обязательны

2021-11-18 14:23 UTC, chrn-feip requested changes

2021-11-18 14:23 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $comments = $post->comments()->orderByDesc('created_at')->paginate(2);
Нужна ещё сортировка по id как гарантия однозначности. Это можно запихнуть в scopeOrdered и вызывать просто его на отношении comments

2021-11-19 08:18 UTC, chrn-feip requested changes

2021-11-19 08:18 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
Вы вот прямо проверили кейс с слагом одного поста и id коммента от другого и получили missing? А в при корректных значениях пост и комментарий попадают сюда корректные и эта проверка действительно становится не нужна?

2021-11-19 08:18 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $comments = $post->comments()->ordered()->paginate(2);
В модели комментария нет scopeOrdered, не закоммитили или не потестировали.
Проверьте все остальные комментарии к PR, которые не закрыты, дайте ответ.

2021-11-19 10:35 UTC, f-m-t-t-m commented on database/seeders/DatabaseSeeder.php
> +            UserSeeder::class,
Да, не падает.

2021-11-19 10:37 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
А проверяли слаг несуществующего поста в маршруте комментария?

2021-11-19 10:40 UTC, f-m-t-t-m commented on app/Http/Controllers/CommentController.php
> +        $comments = $post->comments()->ordered()->paginate(2);
Не закоммитил модель.

2021-11-19 10:43 UTC, f-m-t-t-m commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
Да, если комментарий не принадлежит этому посту, то получаю missing. Если принадлежит, то комментарий.

2021-11-19 11:05 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
А если сам пост не найден?

2021-11-19 12:28 UTC, f-m-t-t-m commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
Если обращаться к несуществующему посту в маршруте комментария, то будет миссинг на комментарий.

2021-11-19 12:33 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
А ваш коллега mikairyuu говорит о другом поведении :) Что выбрасывается штатный 404, который html, а не желаемый вами json. Кто не прав?

2021-11-19 14:07 UTC, f-m-t-t-m commented on app/Http/Controllers/CommentController.php
> -        if ($post->id !== $comment->post_id) {
https://imgur.com/a/jYt56gg

2021-11-19 14:47 UTC, merged